package in.aarogya.health.integration;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

import org.springframework.stereotype.Component;

@Component
public class MockAbdmHealthRecordAdapter implements AbdmHealthRecordAdapter {

    @Override
    public HealthIntegrationDescriptor descriptor() {
        return new HealthIntegrationDescriptor(
            "ABDM_MOCK",
            "ABDM / ABHA architecture demo",
            "MOCK",
            false,
            "FHIR-compatible normalization boundary",
            "Synthetic local demo only. No live ABDM, ABHA, HIE-CM, PHR or government network request is made."
        );
    }

    @Override
    public String createExternalSubjectRef(UUID userId) {
        var compact = userId.toString().replace("-", "");
        return "DEMO-SUBJECT-" + compact.substring(0, 12).toUpperCase();
    }

    @Override
    public List<ExternalHealthRecord> fetchRecords(UUID userId) {
        return List.of(
            new ExternalHealthRecord(
                "DEMO-LAB-2026-09-18",
                "LAB_REPORT",
                "Preventive lab panel · demo",
                "Synthetic laboratory record generated by the mock ABDM adapter for architecture testing. These are not the user's real clinical results.",
                LocalDate.of(2026, 9, 18),
                "Demo Health Network",
                "Mock Interoperability Facility",
                "DiagnosticReport",
                List.of(
                    new ExternalHealthObservation(
                        "DEMO-OBS-HBA1C",
                        "HBA1C",
                        "AAROGYA_DEMO",
                        "HbA1c",
                        new BigDecimal("5.4"),
                        null,
                        "%",
                        null,
                        Instant.parse("2026-09-18T05:30:00Z")
                    ),
                    new ExternalHealthObservation(
                        "DEMO-OBS-HB",
                        "HEMOGLOBIN",
                        "AAROGYA_DEMO",
                        "Haemoglobin",
                        new BigDecimal("13.8"),
                        null,
                        "g/dL",
                        null,
                        Instant.parse("2026-09-18T05:30:00Z")
                    )
                )
            ),
            new ExternalHealthRecord(
                "DEMO-VITALS-2026-09-01",
                "MEASUREMENT_SET",
                "Vital measurements · demo",
                "Synthetic vital-sign record for local interoperability demonstration only.",
                LocalDate.of(2026, 9, 1),
                "Demo Health Network",
                "Mock Interoperability Facility",
                "Observation",
                List.of(
                    new ExternalHealthObservation(
                        "DEMO-OBS-WEIGHT",
                        "BODY_WEIGHT",
                        "AAROGYA_DEMO",
                        "Body weight",
                        new BigDecimal("68.4"),
                        null,
                        "kg",
                        null,
                        Instant.parse("2026-09-01T04:30:00Z")
                    ),
                    new ExternalHealthObservation(
                        "DEMO-OBS-SBP",
                        "SYSTOLIC_BP",
                        "AAROGYA_DEMO",
                        "Systolic blood pressure",
                        new BigDecimal("118"),
                        null,
                        "mmHg",
                        null,
                        Instant.parse("2026-09-01T04:30:00Z")
                    ),
                    new ExternalHealthObservation(
                        "DEMO-OBS-DBP",
                        "DIASTOLIC_BP",
                        "AAROGYA_DEMO",
                        "Diastolic blood pressure",
                        new BigDecimal("76"),
                        null,
                        "mmHg",
                        null,
                        Instant.parse("2026-09-01T04:30:00Z")
                    )
                )
            ),
            new ExternalHealthRecord(
                "DEMO-CONSULT-2026-08-12",
                "OP_CONSULT",
                "Outpatient consultation · demo",
                "Synthetic consultation summary used only to demonstrate record provenance and timeline behavior.",
                LocalDate.of(2026, 8, 12),
                "Demo Health Network",
                "Mock Interoperability Facility",
                "DocumentReference",
                List.of()
            )
        );
    }
}
